package com.kerfaiyassine.stadium.enums;

public enum OperationType {

    // STRUCTURE
    FOUNDATION_INSPECTION,
    STAND_CONSTRUCTION,
    ROOF_INSTALLATION,
    STRUCTURAL_REPAIR,
    LOAD_BEARING_ASSESSMENT,

    // TURF
    GRASS_INSTALLATION,
    HYBRID_TURF_INSTALLATION,
    SYNTHETIC_SURFACE_INSTALLATION,
    TURF_MAINTENANCE,
    SURFACE_REPLACEMENT,

    // DRAINAGE
    IRRIGATION_SYSTEM_INSTALL,
    DRAINAGE_SYSTEM_INSTALL,
    WATERPROOFING,
    DRAINAGE_MAINTENANCE,

    // LIGHTING
    FLOODLIGHT_INSTALLATION,
    SCOREBOARD_INSTALLATION,
    LIGHTING_UPGRADE,
    ELECTRICAL_MAINTENANCE,

    // SAFETY
    SAFETY_AUDIT,
    ACCESSIBILITY_UPGRADE,
    EMERGENCY_EXIT_INSTALLATION,
    CROWD_CONTROL_SETUP,
    FIRE_SAFETY_INSPECTION,

    // PROJECT_MANAGE
    BUDGET_PLANNING,
    SCHEDULE_MANAGEMENT,
    CONTRACTOR_SUPERVISION,
    PROGRESS_REPORTING,
    COST_ESTIMATION,

    // REGULATION
    FIFA_COMPLIANCE_AUDIT,
    UEFA_COMPLIANCE_AUDIT,
    LOCAL_CODE_INSPECTION,
    CERTIFICATION_RENEWAL,
    PERMIT_ACQUISITION,

    // INNOVATION
    SMART_TECH_INTEGRATION,
    RETRACTABLE_ROOF_INSTALL,
    VAR_SYSTEM_SETUP,
    DIGITAL_INFRASTRUCTURE_UPGRADE,

    // SUSTAINABILITY
    SOLAR_PANEL_INSTALLATION,
    RAINWATER_HARVESTING_SETUP,
    LEED_CERTIFICATION_PROCESS,
    ENERGY_EFFICIENCY_AUDIT,
    WASTE_MANAGEMENT_SETUP,
}